name: 'Setup Java & Build'
description: 'Sets up Java and runs Maven build'

inputs:
  java-version:
    description: 'Java version'
    required: true
    default: '17'

runs:
  using: 'composite'
  steps:
    - name: Setup Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
